const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const source = fs.readFileSync(path.join(root, 'scripts/app-window.js'), 'utf8')

test('app window runs as a desktop-style launcher instead of the old browser page', () => {
    assert.match(source, /--app=\$\{url\}/)
    assert.match(source, /APP_WINDOW_WIDTH = 1500/)
    assert.match(source, /APP_WINDOW_HEIGHT = 900/)
    assert.match(source, /--window-size=/)
    assert.match(source, /windowsHide:\s*true/)
    assert.match(source, /assets', 'logo\.png'/)
    assert.match(source, /rel="icon"/)
    assert.match(source, /\/manifest\.json/)
    assert.match(source, /chromium\.executablePath/)
    assert.match(source, /resolveBundledChromium\(\)/)
    assert.match(source, /spawn\(process\.execPath,\s*\['\.\/dist\/index\.js',\s*'--ui-child'\]/)
    assert.match(source, /POST' && req\.url === '\/api\/start'/)
    assert.match(source, /POST' && req\.url === '\/api\/stop'/)
    assert.match(source, /POST' && req\.url === '\/api\/close'/)
    assert.match(source, /POST' && req\.url === '\/api\/open-accounts'/)
    assert.match(source, /POST' && req\.url === '\/api\/open-discord'/)
    assert.match(source, /Rewards Bot/)
    assert.match(source, /id="view-accounts"/)
    assert.match(source, /id="view-console"/)
    assert.match(source, /id="view-settings"/)
    assert.match(source, /id="view-core"/)
    assert.match(source, /id="btn-run"/)
    assert.match(source, /id="btn-stop"/)
    assert.doesNotMatch(source, /License key or empty response/)
    assert.match(source, /height:\s*100vh/)
    assert.match(source, /MSRB_APP_NO_OPEN/)
    assert.doesNotMatch(source, /id="modal"|id="lic-input"|id="lic-submit"|id="lic-skip"/)
    assert.doesNotMatch(source, /req\.url === '\/api\/input'/)
})

test('Rewards Desk local API requires a process token and validates request boundaries', () => {
    assert.match(source, /crypto\.randomBytes\(32\)\.toString\('base64url'\)/)
    assert.match(source, /x-msrb-token/)
    assert.match(source, /crypto\.timingSafeEqual/)
    assert.match(source, /Invalid host/)
    assert.match(source, /Invalid origin/)
    assert.match(source, /MAX_API_BODY_BYTES = 64 \* 1024/)
    assert.match(source, /Request body too large/)
})

test('Rewards Desk presents two coherent startup modes and desktop-like interaction', () => {
    assert.match(source, /id="tog-startup-desk"/)
    assert.match(source, /id="tog-startup-agent"/)
    assert.match(source, /Core remote access/)
    assert.doesNotMatch(source, /id="tog-bgAgent"|data-cfg="dashboardSync"/)
    assert.match(source, /document\.addEventListener\('contextmenu'/)
    assert.match(source, /user-select:none/)
    assert.match(source, /input,textarea,select,\.console-box\{user-select:text/)
    assert.match(source, /closest\('#console-box'\)/)
    assert.match(source, /core-enhanced/)
    assert.match(source, /requestAgentRun/)
    assert.match(source, /subscribeToAgentLogs/)
})

test('Rewards Desk opens before slow Core and OS-vault initialization', () => {
    assert.match(source, /runCoreLicenseWorker/)
    assert.match(source, /account-storage-worker\.js/)
    assert.match(source, /if \(process\.env\.MSRB_APP_NO_OPEN !== '1'\) openAppWindow\(url\)[\s\S]*initializeDeskInBackground\(\)/)
    assert.doesNotMatch(source, /require\(corePath\)/)
})

test('Rewards Desk exposes visible protection, Core deactivation, and desktop installation controls', () => {
    assert.match(source, /id="storage-toggle">Disable encryption/)
    assert.match(source, /id="lic-view-manage"/)
    assert.match(source, /\/api\/license\/deactivate/)
    assert.match(source, /id="install-btn"/)
    assert.match(source, /id="desktop-uninstall"/)
    assert.match(source, /app-boot/)
    assert.match(source, /if \(_bootOverlayReleased\) return/)
    assert.match(source, /accountStorageRequest/)
    assert.doesNotMatch(source, /install-reveal|install-status-taskbar|Create or repair shortcuts/)
    assert.match(source, /\/api\/desktop-install/)
    assert.match(source, /data\.complete === true/)
    assert.match(source, /webhook\.runSummary\.discordUrl/)
    assert.doesNotMatch(source, /Include Core upgrade pitch/)
})

test('Rewards Desk uses one Core activation flow and synchronizes plugin state', () => {
    assert.match(source, /if \(promptVisible && !_licensePromptVisible\) licOpenOverlay\('key'\)/)
    assert.match(source, /if \(s\.hasLicenseCache \|\| s\.corePluginEnabled === false\)/)
    assert.match(source, /POST' && req\.url === '\/api\/license\/skip'/)
    assert.match(source, /setPluginEnabled\('core', false\)/)
    assert.match(source, /setPluginEnabled\('core', true\)/)
    assert.match(source, /if \(state\.licensePrompt\.visible\) sendInput\(parsed\.key \|\| ''\)/)
    assert.match(source, /if \(state\.licensePrompt\.visible\) sendInput\(''\)/)
    assert.match(source, /coreEnabled: isPluginEnabled\('core'\)/)
})
