const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const source = fs.readFileSync(path.join(root, 'scripts/app-window.js'), 'utf8')

test('app window runs as a desktop-style launcher instead of the old browser page', () => {
    assert.match(source, /--app=\$\{url\}/)
    assert.match(source, /windowsHide:\s*true/)
    assert.match(source, /spawn\(process\.execPath,\s*\['\.\/dist\/index\.js',\s*'--ui-child'\]/)
    assert.match(source, /POST' && req\.url === '\/api\/start'/)
    assert.match(source, /POST' && req\.url === '\/api\/stop'/)
    assert.match(source, /POST' && req\.url === '\/api\/close'/)
    assert.match(source, /Rewards Bot/)
    assert.match(source, /Powered by Core/)
    assert.match(source, /Today's Progress/)
    assert.match(source, /Active Account/)
    assert.match(source, /Recent Activity/)
    assert.match(source, /Start Run/)
    assert.match(source, /Stop/)
    assert.match(source, /License key or empty response/)
})
