const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const source = fs.readFileSync(path.join(root, 'scripts/app-window.js'), 'utf8')

test('app window runs as a desktop-style launcher instead of the old browser page', () => {
    assert.match(source, /--app=\$\{url\}/)
    assert.match(source, /APP_WINDOW_WIDTH = 1500/)
    assert.match(source, /APP_WINDOW_HEIGHT = 900/)
    assert.match(source, /--start-maximized/)
    assert.match(source, /windowsHide:\s*true/)
    assert.match(source, /assets', 'logo\.png'/)
    assert.match(source, /rel="icon"/)
    assert.match(source, /\/manifest\.json/)
    assert.match(source, /chromium\.executablePath/)
    assert.match(source, /resolveBundledChromium\(\)/)
    assert.match(source, /spawn\(process\.execPath,\s*\['\.\/dist\/index\.js',\s*'--ui-child'\]/)
    assert.match(source, /LICENSE_KEY: pendingLicenseKey/)
    assert.match(source, /POST' && req\.url === '\/api\/start'/)
    assert.match(source, /POST' && req\.url === '\/api\/stop'/)
    assert.match(source, /POST' && req\.url === '\/api\/close'/)
    assert.match(source, /POST' && req\.url === '\/api\/open-accounts'/)
    assert.match(source, /POST' && req\.url === '\/api\/open-discord'/)
    assert.match(source, /Rewards Bot/)
    assert.match(source, /id="view-accounts"/)
    assert.match(source, /id="view-console"/)
    assert.match(source, /id="view-settings"/)
    assert.match(source, /id="view-core"/)
    assert.match(source, /id="btn-run"/)
    assert.match(source, /id="btn-stop"/)
    assert.doesNotMatch(source, /License key or empty response/)
    assert.match(source, /height:\s*100vh/)
    assert.match(source, /MSRB_APP_NO_OPEN/)
})

test('Rewards Desk local API requires a process token and validates request boundaries', () => {
    assert.match(source, /crypto\.randomBytes\(32\)\.toString\('base64url'\)/)
    assert.match(source, /x-msrb-token/)
    assert.match(source, /crypto\.timingSafeEqual/)
    assert.match(source, /Invalid host/)
    assert.match(source, /Invalid origin/)
    assert.match(source, /MAX_API_BODY_BYTES = 64 \* 1024/)
    assert.match(source, /Request body too large/)
})
