const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const source = fs.readFileSync(path.resolve(__dirname, '../src/index.ts'), 'utf8')

test('run summary includes detailed Core coupon impact', () => {
    assert.match(source, /coupons:\s*AppliedCoupon\[\]/)
    assert.match(source, /this\.userData\.coreStats\.coupons\.push\(\.\.\.couponResult\.coupons\)/)
    assert.match(source, /Core coupons:/)
    assert.match(source, /formatCouponSummary/)
    assert.match(source, /coupon savings were not handled/)
    assert.match(source, /applied coupon names/)
    assert.match(source, /sendDiscordEmbed/)
    assert.match(source, /summaryConfig\.discordUrl/)
    assert.match(source, /buildRunSummaryEmbed/)
    assert.match(source, /includeCoreComparison \?\? summaryConfig\.includeCorePitch \?\? true/)
    assert.doesNotMatch(source, /sendDiscord\(this\.config\.webhook\.discord\.url, message/)
})
